name: fresh resolvers

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master
  schedule:
    - cron: '0 0 */3 * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v2

    - name: Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python3 -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Install MassDNS
      run: |
        sudo apt-get update
        git clone https://github.com/blechschmidt/massdns.git
        cd massdns
        make
        sudo make install

    - name: Run fresh.py
      run: |
        python3 fresh.py -o resolvers_clean.txt
      working-directory: /home/runner/work/fresh.py/fresh.py
      continue-on-error: true

    - name: Produce and move resolvers_clean.txt
      run: |
        mkdir -p output
        mv resolvers_clean.txt output/resolvers_clean.txt

    - name: Commit and push output file
      run: |
        git config --global user.name 'github-actions'
        git config --global user.email 'github-actions@github.com'
        git add output/resolvers_clean.txt
        git commit -m 'Add resolvers_clean.txt'
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

# trigger
